[global]
# Set to "-" to disable normal logging messages like "direnv: loading .envrc"
log_format = "-"
# Set to true to hide the diff of the environment variables when loading the .envrc
hide_env_diff = true
# Use with log_format = "-" to ensure no other logs slip through (optional)
log_filter = "^$"

